### PR TITLE
Improved design diagrams.

### PR DESCRIPTION
**Pull request by Bplotka**
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by Bplotka** [comment]
You can see outcome here: https://github.com/improbable-eng/kedge/blob/6bf4e84991b8362909b9fa70619ec70b3d978145/README.md

**Comment by domgreen** [comment]
Think I would prefer it in colour.

**Comment by Bplotka** [comment]
Yeah. In this way we have consistent coloring.

**Comment by domgreen** [comment]
Makes sense that they are consistent .. tooks good to me if that is the colour scheme for the post. Diagrams are both good and fit well with the blog post descriptions of what is happening 👍

**Pull request merged**
